name: Autofix Vite SW + Postbuild (direct)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          npm ci
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f Files/requirements.txt ]; then pip install -r Files/requirements.txt; fi

      - name: First test/build (best effort)
        id: first
        continue-on-error: true
        env:
          BASE_URL: "/${{ github.event.repository.name }}/"
        run: |
          pytest -q || echo "::warning::pytest failed (will try to autofix)"
          npm run build || echo "::warning::npm build failed (will try to autofix)"

      - name: Apply autofix
        run: |
          set -e
          # 1) Ensure SW file
          mkdir -p public
          if [ ! -f public/sw.js ]; then
            cat > public/sw.js <<'JS'
self.addEventListener('install', () => self.skipWaiting && self.skipWaiting());
self.addEventListener('activate', () => self.clients && self.clients.claim && self.clients.claim());
JS
          fi

          # 2) Fix postbuild to copy 404 + manifest
          node - <<'NODE'
const fs=require('fs');const p='package.json';
const pkg=JSON.parse(fs.readFileSync(p,'utf8'));pkg.scripts=pkg.scripts||{};
pkg.scripts.postbuild="cp -f dist/index.html dist/404.html && cp -f dist/.vite/manifest.json dist/manifest.json";
fs.writeFileSync(p,JSON.stringify(pkg,null,2)+'\n');console.log('postbuild set');
NODE

          # 3) Replace SW registration to use BASE_URL
          FILES=$(grep -RIl --include=\*.ts --include=\*.js "new URL(['\"]sw.js['\"], *import.meta.url)" src 2>/dev/null || true)
          if [ -n "$FILES" ]; then
            perl -0777 -i -pe "s/new URL\\((['\"])sw\\.js\\1,\\s*import\\.meta\\.url\\)/import.meta.env.BASE_URL + 'sw.js'/g" $FILES
          fi

      - name: Re-test and build (must pass)
        env:
          BASE_URL: "/${{ github.event.repository.name }}/"
        run: |
          set -e
          pytest -q
          npm run build
          test -f dist/404.html
          test -f dist/manifest.json

      - name: Commit & push to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "autofix: ensure SW + postbuild; BASE_URL registration [skip ci]"
          commit_user_name: "autofix-bot"
          commit_user_email: "autofix-bot@users.noreply.github.com"
          file_pattern: |
            public/sw.js
            package.json
            src/**/*.ts
            src/**/*.js
            dist/404.html
            dist/manifest.json
