name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write      # für deploy-pages
  id-token: write   # OIDC für deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4 pinned

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0 pinned
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Artefakt für Pages hochladen (nur dist/)
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@69d9d6d3a4f1d6a605c60d67e0f15eb71e0c1af8  # v3.0.0 pinned

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@668f0d2fcf7b7a92d58d3e9e9d6c5b9f27a1de92  # v4.0.0 pinned